### ISSUE TITLE
GoLang and NodeJS API Wrapper

### ISSUE THREAD

**Issue by HPaulson** [JLuboff/TheSimpsonsQuoteAPI#1]
Hey there! I created a GO Lang and NodeJs SDK for this API! Figured i would share this with you!

GO Lang: https://github.com/C0braD3v/TheSimpsonsQuoteAPI-SDK-GO
NODE: https://github.com/C0braD3v/TheSimpsonsQuoteAPI-SDK-NODE
NODE (NPM): https://www.npmjs.com/package/simpsons-quote-api

**Comment by JLuboff** [comment]
@C0braD3v Thats awesome! When I get a chance I'll add them to the Read Me for others to see, or fill free to submit a PR!

**Comment by HPaulson** [comment]
Awesome! Thanks man! This API is super fun and cool, so thought it would be fun to make some SDKs. Maybe I’ll do one for python too :)

**Comment by HPaulson** [comment]
Ive gone ahead and submitted PR #2! Sorry it took so long!

**Comment by JLuboff** [comment]
@C0braD3v  No Worries, thanks for the PR!

See f85c2bb for PR merge
