### ISSUE TITLE
Get quotes by character

### ISSUE THREAD

**Issue by gennaro-tedesco** [JLuboff/TheSimpsonsQuoteAPI#7]
I found this nice little project and I would like to integrate it in a cli of mine (say along the same lines of the Go wrapper already available). Is it possible to retrieve quotes by character? 

Ideally I could still fetch N quotes and then sub-filter, however one would spare a lot of post-processing if the endpoints might be selected accordingly beforehand. Is it possible?

**Comment by JLuboff** [comment]
I can update the API to allow for filtered results by character(s). My thought would be to just have it be another query parameter in the form of an array ie `characters=[homer simpson, bart simpson]` 
I'm guessing it would be more ideal to allow for partial names? Meaning providing `Homer` and `Homer Simpson` should yield the same result set?
Let me know and I can probably knock this out fairly quickly.

**Comment by gennaro-tedesco** [comment]
For my particular use case character parameters as one single character string only is sufficient, so no need to allow complexity of a list. The user will be prompted with a selection menu (along the lines of [promptui](https://github.com/manifoldco/promptui)) and will select one character which ideally will be querying the `quotes?<character>&count` (which also solves the problem of partial names: names will be fixed in the menu choices so no particular need to allow for substrings).

Thank you for being so responsive!

**Comment by JLuboff** [comment]
@gennaro-tedesco API has been updated to include a `character` query param. I made it so that it can be partial names or of course the full name. Check out the updated ReadMe or https://thesimpsonsquoteapi.glitch.me/ for more details. Enjoy!

**Comment by gennaro-tedesco** [comment]
Thank you very much, I am trying it out right now and I should have a draft of my project ready soon, so that you can check where your work is going :).

P. S. do we have a list of all included characters somewhere?

**Comment by JLuboff** [comment]
I don't have an active list, but pulled down all quotes (there are currently 50) and filtered it down. 

There are one or more quotes from the following:   Waylon Smithers, Chief Wiggum, Mr. Burns, Homer Simpson, Principal Skinner, Moe Szyslak, Bart Simpson, Apu Nahasapeemapetilon, Ralph Wiggum, Comic Book Guy, Marge Simpson, Troy McClure, Rainier Wolfcastle, Lisa Simpson, Mayor Quimby, Groundskeeper Willie, Otto, Abe Simpson, Milhouse Van Houten, Frank Grimes, Nelson Muntz, Duffman, Dr. Nick

I look forward to seeing your project :)

**Comment by gennaro-tedesco** [comment]
Let me introduce to you [happyfish](https://github.com/gennaro-tedesco/happyfish): it is a recreational project that I am building to explore some Go frameworks and I thought that yours would be a nice usecase to selection prompts and the like. I acknowledged attribution to your project in the README; feel free to cite it too if you like :)

There is a first release already, so you should be able to even install it already via `go get`.
